server:
  port: 8090
spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:mysql://localhost:3306/everycharge
    username: <NEED_TO_INPUT>
    password: <NEED_TO_INPUT>
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password: 1234
  sql:
    init:
      mode: always
      continue-on-error: true
      data-locations: classpath:/sql/data1.sql, classpath:/sql/data2.sql, classpath:/sql/data3.sql
logging:
  level:
    com.ll.everycharge: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: INFO
    org.springframework.transaction.interceptor: TRACE
custom:
  aws:
    s3:
      bucket: dev-bucket-everycharge-1
      stack.auto: false
      region.static: ap-northeast-2