INSERT INTO car (manufacturer, car_model, battery, charge_time_fast, charge_time_slow, max_board, charge_way_fast,
                 charge_way_slow, img_url)
VALUES ('VOLVO', 'VOLVO S90 T8', '미정의', '미정의', '미정의', '미정의', '미정의', '미정의',
        'https://dev-bucket-eticharge-1.s3.ap-northeast-2.amazonaws.com/carImg/VOLVO+S90+T8.png'),
       ('BMW', 'BMW X3 xDRIVE30e', '미정의', '미정의', '미정의', '미정의', '미정의', '미정의',
        'https://dev-bucket-eticharge-1.s3.ap-northeast-2.amazonaws.com/carImg/BMW+X3.png'),
       ('BMW', 'BMW 530e PHEV', '10.8', '미정의', '미정의', '미정의', '미정의', '미정의',
        'https://dev-bucket-eticharge-1.s3.ap-northeast-2.amazonaws.com/carImg/BMW+530e+PHEV.png'),
       ('벤츠', '벤츠 EQC400', '80', '약 40분', '약 11시간', '미정의', '미정의', '미정의',
        'https://dev-bucket-eticharge-1.s3.ap-northeast-2.amazonaws.com/carImg/GLC+350e+PHEV.png'),
       ('벤틀리', '벤테이가 PHEV', '17.3', '미정의', '미정의', '미정의', '미정의', '미정의',
        'https://dev-bucket-eticharge-1.s3.ap-northeast-2.amazonaws.com/carImg/%EB%B2%A4%ED%85%8C%EC%9D%B4%EA%B0%80.png'),
       ('조이롱코리아', 'E6', '60', '미정의', '미정의', '미정의', '미정의', '미정의',
        'https://dev-bucket-eticharge-1.s3.ap-northeast-2.amazonaws.com/carImg/E6.png'),
       ('BMW', 'BMW 7 PHEV', '미정의', '미정의', '미정의', '미정의', '미정의', 'AC완속(5핀)',
        'https://dev-bucket-eticharge-1.s3.ap-northeast-2.amazonaws.com/carImg/BMW+7+PHEV.png'),
       ('벤츠', 'GLC 350e PHEV', '미정의', '미정의', '미정의', '미정의', '미정의', 'AC완속(5핀)',
        'https://dev-bucket-eticharge-1.s3.ap-northeast-2.amazonaws.com/carImg/GLC+350e+PHEV.png'),
       ('BMW', 'i3', '21.3', '약 30분', '약 3~4시간', '준중형 5인승', 'DC콤보(급속)', 'AC완속(5핀)',
        'https://dev-bucket-eticharge-1.s3.ap-northeast-2.amazonaws.com/carImg/i3.png'),
       ('르노삼성', 'SM3 ZE', '26.6', '약 30분', '약 3~4시간', '중형 4인승', 'AC3상(급속)', 'AC완속(7핀)',
        'https://dev-bucket-eticharge-1.s3.ap-northeast-2.amazonaws.com/carImg/SM3+ZE.png'),
       ('기아', '니로EV', '64', '약 1시간', '약 9시간', '5인승', 'DC콤보(급속)', 'AC완속(5핀)',
        'https://dev-bucket-eticharge-1.s3.ap-northeast-2.amazonaws.com/carImg/%EB%8B%88%EB%A1%9CEV.png'),
       ('기아', '레이EV', '16.4', '약 25분', '약 6시간', '경승용 4인승', 'DC차데모(급속)', 'AC완속(5핀)',
        'https://dev-bucket-eticharge-1.s3.ap-northeast-2.amazonaws.com/carImg/%EB%A0%88%EC%9D%B4EV.png'),
       ('닛산', '리프EV', '24.4', '약 30분', '약 5시간', '준중형 5인승', 'DC차데모(급속)', 'AC완속(5핀)',
        'https://dev-bucket-eticharge-1.s3.ap-northeast-2.amazonaws.com/carImg/%EB%A6%AC%ED%94%84EV.png'),
       ('테슬라', '테슬라_모델S', '90', '약 30분', '약 3시간', '5인승', '미정의', 'AC완속(7핀)',
        'https://dev-bucket-eticharge-1.s3.ap-northeast-2.amazonaws.com/carImg/%ED%85%8C%EC%8A%AC%EB%9D%BC_%EB%AA%A8%EB%8D%B8S.png'),
       ('한국GM', '볼트PHEV', '미정의', '미정의', '미정의', '미정의', '미정의', 'AC완속(5핀)',
        'https://dev-bucket-eticharge-1.s3.ap-northeast-2.amazonaws.com/carImg/%EB%B3%BC%ED%8A%B8PHEV.png'),
       ('한국GM', '볼트EV', '60', '약 1시간', '약 9시간', '5인승', 'DC콤보(급속)', 'AC완속(5핀)',
        'https://dev-bucket-eticharge-1.s3.ap-northeast-2.amazonaws.com/carImg/%EB%B3%BC%ED%8A%B8EV.png'),
       ('기아', '쏘울EV', '27', '약 33분', '약 7시간', '준중형 5인승', 'DC차데모(급속)', 'AC완속(5핀)',
        'https://dev-bucket-eticharge-1.s3.ap-northeast-2.amazonaws.com/carImg/%EC%8F%98%EC%9A%B8EV.png'),
       ('한국GM', '스파크EV', '미정의', '미정의', '미정의', '미정의', '미정의', 'AC완속(5핀)',
        'https://dev-bucket-eticharge-1.s3.ap-northeast-2.amazonaws.com/carImg/%EC%8A%A4%ED%8C%8C%ED%81%ACEV.png'),
       ('현대', '쏘나타PHEV', '미정의', '미정의', '미정의', '미정의', '미정의', 'AC완속(5핀)',
        'https://dev-bucket-eticharge-1.s3.ap-northeast-2.amazonaws.com/carImg/%EC%8F%98%EB%82%98%ED%83%80PHEV.png'),
       ('현대', '아이오닉PHEV', '미정의', '미정의', '미정의', '미정의', '미정의', 'AC완속(5핀)',
        'https://dev-bucket-eticharge-1.s3.ap-northeast-2.amazonaws.com/carImg/%EC%95%84%EC%9D%B4%EC%98%A4%EB%8B%89PHEV.png'),
       ('현대', '아이오닉EV(2016년도)', '28', '약 23분', '약 5시간', '준중형 5인승', 'DC차데모(급속)', 'AC완속(5핀)',
        'https://dev-bucket-eticharge-1.s3.ap-northeast-2.amazonaws.com/carImg/%EC%95%84%EC%9D%B4%EC%98%A4%EB%8B%89EV(2016%EB%85%84%EB%8F%84).png'),
       ('현대', '아이오닉EV(2017이후)', '28', '약 23분', '약 5시간', '준중형 5인승', 'DC콤보(급속)', 'AC완속(5핀)',
        'https://dev-bucket-eticharge-1.s3.ap-northeast-2.amazonaws.com/carImg/%EC%95%84%EC%9D%B4%EC%98%A4%EB%8B%89EV(2017%EC%9D%B4%ED%9B%84).png'),
       ('현대', '코나EV', '64', '약 1시간', '약 9시간', '5인승', 'DC콤보(급속)', 'AC완속(5핀)',
        'https://dev-bucket-eticharge-1.s3.ap-northeast-2.amazonaws.com/carImg/%EC%BD%94%EB%82%98EV.png'),
       ('벤츠', '벤츠 s560e', '13.5', '미정의', '미정의', '미정의', '미정의', '미정의',
        'https://dev-bucket-eticharge-1.s3.ap-northeast-2.amazonaws.com/carImg/%EB%B2%A4%EC%B8%A0+s560e.png'),
       ('FORD', '포드 익스플로러 플러그인 하이브리드', '', '미정의', '미정의', '7인승', '미정의', '미정의',
        'https://dev-bucket-eticharge-1.s3.ap-northeast-2.amazonaws.com/carImg/%ED%8F%AC%EB%93%9C+%EC%9D%B5%EC%8A%A4%ED%94%8C%EB%A1%9C%EB%9F%AC+%ED%94%8C%EB%9F%AC%EA%B7%B8%EC%9D%B8+%ED%95%98%EC%9D%B4%EB%B8%8C%EB%A6%AC%EB%93%9C.png'),
       ('르노삼성', '조에', '미정의', '약 30분', '약 9시간 30분', '5인승', 'DC콤보(급속)', '미정의',
        'https://dev-bucket-eticharge-1.s3.ap-northeast-2.amazonaws.com/carImg/%EC%A1%B0%EC%97%90.png');

